apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-yd5j
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0043-tenant/tkrw-pr712-0075-0043-app/devfile-sample-yd5j@sha256:a1d6800a4eda3c74ab74705aee6e185430086008ffbb7cbff7a2a9686566e5af
        name: my-nodejs
        resources: {}
status: {}
